"""Give the client's windows the product icon instead of Tk's default feather or Python's logo.

Mostly tkinter, hence the name, but the Windows-identity half (``claim_app_identity``,
``apply_taskbar_icon``) is plain ctypes and serves the pywebview popup shell too — the icon a
Windows user sees belongs to the product, not to whichever toolkit happened to open the window.

Every caller is best-effort by construction: a missing asset, an old Tk, or a headless display must
never be the reason a window fails to open. The icon is decoration; the window is the product.

Windows is the platform this exists for — its title bar, taskbar button and Alt-Tab card all read
the window icon, and with nothing set they show Tk's feather, which looks like a stray Python
script rather than the product. macOS draws no icon in a title bar at all (only document windows
get a proxy icon), so there ``iconphoto`` is a no-op and the real macOS icons are the app bundle's
``AppIcon.icns`` and the menu-bar image — both generated by the same ``desktop/icons/make_icons.py``
from the same master, so the three surfaces cannot drift apart.
"""

from __future__ import annotations

import platform
from pathlib import Path
from typing import Any, Optional

# client/tk_icon.py → the body root is one level up; the icons ship under desktop/icons/.
# Deliberately NOT resolved at module scope. panel.py imports this module with a plain top-level
# `from client import runner, tk_icon`, so anything that raises out here takes the stop panel down
# at import — the exact failure this module exists to make impossible. Path.resolve() touching the
# filesystem is a small risk, but "small" is the wrong bar for decoration.
_ICON_DIR = Path(__file__).parent.parent / "desktop" / "icons"
ICO_PATH = _ICON_DIR / "logo.ico"
PNG_PATH = _ICON_DIR / "logo-256.png"
# The macOS Dock tile. Multi-resolution and already a rounded white tile rather than bare
# transparency, which is the shape the Dock expects — see the generator's notes.
ICNS_PATH = _ICON_DIR / "AppIcon.icns"

# Windows groups taskbar buttons by AppUserModelID, and takes the button's icon from the app that
# AUMID identifies — NOT from the window. A plain `pythonw.exe` process inherits Python's own AUMID,
# so the taskbar shows the Python logo no matter what `iconbitmap` did to the title bar. Claiming an
# explicit AUMID detaches us from Python's identity and lets the window icon through. Any stable
# CompanyName.ProductName string works; changing it later re-groups and un-pins existing buttons.
#
# Product-wide on purpose, not per-surface: the stop panel and the popup shell are separate
# processes, and sharing one AUMID is what makes their taskbar buttons group as one application
# instead of standing next to each other as two unrelated ones.
APP_USER_MODEL_ID = "DeepPattern.DecisionEngine"

# WM_SETICON and friends. Spelled out because ctypes has no Win32 constants of its own, and these
# are the whole payload of apply_taskbar_icon below.
_WM_SETICON = 0x0080
_ICON_SMALL, _ICON_BIG = 0, 1
_SM_CXICON, _SM_CXSMICON = 11, 49
_IMAGE_ICON = 1
_LR_LOADFROMFILE = 0x0010


def icon_paths() -> tuple[Optional[Path], Optional[Path]]:
    """(ico, png) — either may be None when the asset is absent (e.g. a partial checkout)."""
    return (ICO_PATH if ICO_PATH.exists() else None,
            PNG_PATH if PNG_PATH.exists() else None)


def claim_app_identity(app_id: str = APP_USER_MODEL_ID) -> bool:
    """Claim an explicit AppUserModelID so the Windows taskbar stops showing the Python icon.

    Call this BEFORE the first window is created — Windows reads the AUMID when a window is
    registered with the shell, so claiming it afterwards leaves the already-registered button alone.

    Returns True when the AUMID was set. No-op everywhere but Windows, and best-effort there: the
    taskbar keeping the Python icon is a cosmetic defect, an unopened window is not."""
    if platform.system() != "Windows":
        return False
    try:
        import ctypes

        ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(app_id)
        return True
    except Exception:  # aqg: top-level boundary — no shell32, old Windows, restricted process
        return False


def apply_dock_icon() -> bool:
    """Give this process a Dock tile instead of whatever the interpreter's is.

    The macOS counterpart to ``claim_app_identity``: a process that shows a Dock icon and never
    sets one gets the icon of the binary that started it, which for us is a bare ``python3`` — the
    same defect the Windows taskbar had. pywebview forces ``NSApplicationActivationPolicyRegular``,
    so the popup IS a Dock app and this is the only thing that fixes its tile.

    Reads ``AppIcon.icns`` because the Dock wants a tile, not bare transparency, and that file is
    already generated as a rounded white one at every resolution the Dock asks for.

    Call this AFTER the toolkit has created its application object, and note that this is the
    opposite of ``claim_app_identity``'s before-the-first-window rule — the Dock reads the tile
    whenever it is set, so nothing is lost by waiting, and waiting is required. ``NSApp()`` is read
    rather than ``NSApplication.sharedApplication()`` precisely so this can never be the call that
    CREATES the application: Tk installs its own ``NSApplication`` subclass and ``Tk_Init`` sends it
    ``-_setup:``, a selector a plain ``NSApplication`` does not implement, so getting there first
    aborts the process with an NSInvalidArgumentException before any window opens.

    Returns True when the icon was set — False when there is no application yet, which is a caller
    ordering bug rather than a missing asset. No-op off macOS, and best-effort there: pyobjc is
    present for the popup (it drives the menu-bar item) but not guaranteed for a bare Tk caller."""
    if platform.system() != "Darwin":
        return False
    try:
        if not ICNS_PATH.exists():
            return False
        from AppKit import NSApp, NSImage

        app = NSApp()
        if app is None:        # nothing has created the NSApplication yet — see above; do NOT
            return False       # create one here, it would poison a Tk that starts afterwards
        image = NSImage.alloc().initWithContentsOfFile_(str(ICNS_PATH))
        if image is None:      # unreadable or not an image; NSImage reports that by returning nil
            return False
        app.setApplicationIconImage_(image)
        return True
    except Exception:  # aqg: top-level boundary — no pyobjc, no window server, no icns
        return False


def native_window_handle(window: Any) -> int:
    """A pywebview window's Win32 handle, or 0 when this build does not expose one.

    ``Window.native`` is the WinForms form on the EdgeChromium backend and its ``Handle`` is an
    IntPtr, which pythonnet will not always convert with a plain ``int()``. Both paths are tried
    because the floor pin is ``pywebview>=4.0`` with no ceiling — a build that renames or drops
    ``native`` must cost us the icon, not the window.

    Lives here rather than beside either caller: the popup shell and the setup dialogs are separate
    packages that must not import each other, and two hand-copied versions of a detail this fiddly
    would drift the moment one of them was fixed."""
    handle = getattr(getattr(window, "native", None), "Handle", None)
    if handle is None:
        return 0
    try:
        return int(handle)
    except TypeError:
        return int(handle.ToInt64())


def apply_taskbar_icon(hwnd: int) -> bool:
    """Give a raw Win32 window the product icon, for the surfaces tkinter never sees.

    ``apply_window_icon`` covers tkinter. The popup shell is pywebview, whose Windows backend is a
    WinForms host with no ``icon`` argument at all (that parameter exists only on the GTK and Qt
    backends), so the only way in is WM_SETICON against the window handle. The popup is frameless,
    so the taskbar button and the Alt-Tab card are the only places this icon is ever drawn.

    Sets both sizes: the taskbar reads the big icon and Alt-Tab the small one, and a window with
    only one of them set falls back to the executable's icon for the other. Returns True when at
    least one was applied — best-effort like everything else here."""
    if platform.system() != "Windows" or not hwnd:
        return False
    try:
        import ctypes

        ico, _ = icon_paths()
        if ico is None:
            return False
        user32 = ctypes.windll.user32
        # Both prototypes must be declared. ctypes defaults an undeclared restype to C `int`, which
        # truncates the 64-bit HICON that LoadImageW returns and hands SendMessageW a torn handle —
        # it would fail only on 64-bit Windows, i.e. everywhere this actually runs.
        user32.LoadImageW.restype = ctypes.c_void_p
        user32.LoadImageW.argtypes = (ctypes.c_void_p, ctypes.c_wchar_p, ctypes.c_uint,
                                      ctypes.c_int, ctypes.c_int, ctypes.c_uint)
        # WPARAM/LPARAM are pointer-sized integers, not pointers: c_size_t and c_ssize_t, so the
        # HICON in lParam survives 64-bit intact without pretending an icon selector is an address.
        user32.SendMessageW.restype = ctypes.c_ssize_t
        user32.SendMessageW.argtypes = (ctypes.c_void_p, ctypes.c_uint,
                                        ctypes.c_size_t, ctypes.c_ssize_t)
        applied = False
        for which, metric in ((_ICON_BIG, _SM_CXICON), (_ICON_SMALL, _SM_CXSMICON)):
            # Ask for the size Windows wants and let LoadImageW pick that entry out of the .ico;
            # the generator writes every standard size, so this is a selection, not a rescale.
            extent = user32.GetSystemMetrics(metric)
            icon = user32.LoadImageW(None, str(ico), _IMAGE_ICON, extent, extent, _LR_LOADFROMFILE)
            if not icon:
                continue
            user32.SendMessageW(ctypes.c_void_p(hwnd), _WM_SETICON, which, icon)
            applied = True
        return applied
    except Exception:  # aqg: top-level boundary — no user32, no such file, a dead hwnd
        return False


def apply_window_icon(root: Any) -> bool:
    """Set ``root``'s icon, and the default for every window this Tk app opens after it.

    Returns True when an icon was applied — for tests and diagnostics; no caller should branch on
    it. Both paths set an APPLICATION-wide default rather than a per-window icon, so the dialogs
    ``tkinter.simpledialog`` / ``tkinter.messagebox`` conjure up inherit it too. That is the whole
    reason the installer's withdrawn root gets an icon at all: nobody ever sees that root, only the
    dialogs parented to it."""
    try:
        # Inside the try, not before it. Path.exists() swallows OSError on 3.12, but "the current
        # implementation happens to be safe" is not the contract this function advertises.
        ico, png = icon_paths()
        if platform.system() == "Windows":
            # `default=` is Windows-only and applies app-wide. It wants a real .ico; the generator
            # writes classic DIB entries because Tk's own ICO reader does not handle the
            # PNG-compressed entries that Vista+ allows.
            if ico is None:
                return False
            root.iconbitmap(default=str(ico))
            return True
        if png is None:
            return False
        # Reading a PNG needs Tk 8.6; 8.5 raises TclError here and the guard below absorbs it. The
        # client requires Python 3.12+, which bundles 8.6 — only a stale system interpreter lands
        # in that branch, and it lands there icon-less rather than broken.
        import tkinter as tk

        image = tk.PhotoImage(master=root, file=str(png))
        root.iconphoto(True, image)
        # Tk does not own the image — drop the last Python reference and the icon blanks out. Park
        # it on the widget so it lives exactly as long as the window does.
        root._de_window_icon = image
        return True
    except Exception:
        # aqg: top-level boundary — every failure mode here (no such file, a TclError on an
        # unreadable image, an ancient Tk without iconphoto) is cosmetic. Swallow it.
        return False
